README.md

Update README.md to add license

---

README.md

1.0.z -> main

---

pom.xml

Update snapshot on main to next tick - 1.1.0

Update pom.xml - Version Tick

---

README.md

Update README.md - Sonar badge addition

Update README.md - Sonar badge addition

---

pom.xml

Update pom.xml to correct version

Update pom.xml to correct version

---

README.md

Updated agent configuration as a section in readme file so that it can be referred in links.

Update agent configuration as a section in readme

---

Jenkinsfile

Added contents to the Jenkinsfile as recommended.
- Reference Jenkinsfile can be found [here](https://github.com/jenkinsci/archetypes/blob/master/common-files/Jenkinsfile).
- And the recommendation can be found [here](https://github.com/jenkins-infra/repository-permissions-updater/issues/3564#issuecomment-1767931442).

Modified Jenkinsfile for the plugin with the recommended contents by infra team.

---

README.md
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/polaris/PolarisParametersService.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/scan/ScanParametersServiceTest.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/scan/polaris/PolarisParametersServiceTest.java

- Updated `polaris_branch_name` as mandatory parameter
- Refactored unit tests accordingly
- Updated readme file

SIGINT-1323: Update polaris branch name as mandatory parameter

---

src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep/config.jelly

Changed `polaris_branch_name` label from Optional to Mandatory.

Changed polaris_branch_name label in the pipeline syntax UI.

---

DeveloperGuide.md
pom.xml
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/factory/ScanParametersFactory.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ApplicationConstants.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/LogMessages.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/BridgeInput.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/Branch.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/Github.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/Host.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/Owner.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/Pull.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/Repository.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/input/github/User.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentService.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/SCMRepositoryService.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/bitbucket/BitbucketRepositoryService.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/github/GithubRepositoryService.java
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig/config.jelly
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig/help-bitbucketCredentialsId.html
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig/help-githubCredentialsId.html
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentServiceTest.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/scm/bitbucket/BitbucketRepositoryServiceTest.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/scm/github/GithubRepositoryServiceTest.java

- Added github cloud and enterprise server integration.
- Added Blackduck PR comment support.
- Added coverity PR comment support.
- Added/modified unit tests.
- Tested BD PR comment for both github cloud and enterprise server.
- TODO: Coverity PR comment for both cloud and enterprise server.

feat: SIGINT-1419 GitHub integration

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig.java

- Fixed two sonarcloud quality gate issues.
- As Coverity doesn't have an endpoint to fetch `access-token`, so couldn't solve 'basic authentication' issue.

Fixed sonarcloud quality gate issues

---

src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig/config.jelly

Updated **Test Connection** button label for global configuration UI.

Update test connection button label for 1.1.z branch

---

src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig/config.jelly

Updated **Test Connection** button label for _main_ branch

Update test connection button label for main branch

---

pom.xml
src/main/java/io/jenkins/plugins/synopsys/security/scan/SecurityScanner.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ApplicationConstants.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/Utility.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentService.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/SCMRepositoryService.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentServiceTest.java

- Made branch source plugin dependencies as optional dependency.
For more information, see the following documentation:
https://www.jenkins.io/doc/developer/plugin-development/optional-dependencies/

Sigint 1486 make branch source plugins optional

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/SCMRepositoryService.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/github/GithubRepositoryService.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/gitlab/GitlabRepositoryService.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/ScannerArgumentServiceTest.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/scm/github/GithubRepositoryServiceTest.java

- While using scripted pipeline syntax, We were having an issue to create pr comment for github and gitlab . In this PR we fixed that.

github integration  issue fixed for scripted

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scm/SCMRepositoryService.java

- Refactored the internal logic to extract the jenkins job name

Refactored the internal logic to extract the jenkins job name

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ErrorCode.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ExceptionMessages.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/ScanParametersService.java
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep/help-polaris_triage.html

Fix exception handling for all job types

Fix exception handling for all job types

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/bridge/BridgeDownload.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/bridge/BridgeInstall.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/coverity/CoverityParametersService.java

- Resolved SonarCloud reliability issues 
- Resolved SonarCloud maintainability issues

Resolve sonarcloud issues

---

src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep/config.jelly

Commented out `return_status` field from pipeline syntax

Comment out return status from pipeline syntax for main branch

---

src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle/help-polaris_triage.html

-  Removed duplicate contents from the tooltip of the `polaris_triage` field.

SIGINT-1577:  Help Information for Polaris Triage field in the Freestyle pipeline contains duplicate details

---

src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle/config.jelly

Checkbox options setting is not getting saved from the Freestyle Job in the UI
Actually the values are getting saved but is not showing up in the FreeStyle UI after the FreeStyle job is saved. 
Added _checked_ condition in Freestyle _config.jelly_ file in checkbox tag so the the saved value gets shown in the UI.

[BugFix] SIGINT-1580: Checkbox options setting is not getting saved from the Freestyle Job in the UI

---

pom.xml
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle/config.jelly

-  Form validations added for the mandatory fields of the freestyle UI.

[Bug Fix]   SIGINT-1578:  No error messages are displayed, if mandatory fields are empty in the Jenkins Freestyle script

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/factory/ScanParametersFactoryTest.java

- set default value as true for return_status parameter

SIGINT-1586: implement review comments on return status

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/PluginParametersHandler.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/LogMessages.java

Refactor method `logMessagesForParameters` to reduce its cognitive complexity

Fix SonarCloud Issue

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/service/scan/polaris/PolarisParametersService.java
src/test/java/io/jenkins/plugins/synopsys/security/scan/service/scan/polaris/PolarisParametersServiceTest.java

- Added POLARIS_PROJECT_NAME_KEY in the PolarisParametersService

Missing property added in the PolarisParametersService

---

src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ApplicationConstants.java
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle/config.jelly
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep/config.jelly

- Added project.source.preserveSymLinks for Polaris upload scan

SIGINT-1938:  Add project.source.preserveSymLinks for Polaris upload scan

---

README.md
pom.xml
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/freestyle/SecurityScanFreestyle.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/extension/pipeline/SecurityScanStep.java
src/main/java/io/jenkins/plugins/synopsys/security/scan/global/ApplicationConstants.java
src/main/resources/index.jelly
src/main/resources/io/jenkins/plugins/synopsys/security/scan/extension/global/ScannerGlobalConfig/config.jelly

- Added a deprecation message to the log.
- Added a deprecation message to the README.
- Updated the global config title to include [DEPRECATED].
- Updated the application name to include [DEPRECATED].
- Updated the pipeline syntax title to include [DEPRECATED].
- Updated the freestyle title to include [DEPRECATED].
- Added "deprecated" topic in the repository

SIGINT-2205: [Deprecate] [Jenkins]: synopsys-security-scan plugin

---

pom.xml

- Updated the revision and changelist

Pom updated for the release

---

pom.xml

- updated the changelist in pom file.

updated the pom file
